baseurl = "//www.vokouond.eu/"
languageCode = "en-us"
theme = "hello-friend-ng"

relativeurls = true
# uglyURLs = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "My Personal Page"
  keywords = "homepage, blog"
  images = [""]

  homeSubtitle = "Security Enthusiast"

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [params.logo]
    logoText     = "$ cd /home/ondra/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    # logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/ondravokoun"

  [[params.social]]
    name = "email"
    url  = "mailto:afk@vokouond.eu"

  [[params.social]]
    name = "github"
    url  = "https://github.com/ImAFK/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/ondrej-vokoun/"

[languages]
  [languages.en]
    title = "Ondřej Vokoun"
    subtitle = "Personal Page"
    keywords = ""
    copyright = ""
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/ondra"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
[menu]
  [[menu.main]]
    identifier = "blog"
    name       = "Travel Blog"
    url        = "https://www.ranecnazadech.cz/"
  [[menu.main]]
    identifier = "about"
    name       = "About me"
    url        = "about/"

[mediaTypes]
  [mediaTypes."text/html"]
  suffixes = ["html"]
[outputFormats]
  [outputFormats.HTML]
  mediaType = "text/html"